server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://*******/server_monitor_data?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: *******
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml





