server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://116.62.7.128:3306/server_monitor_data?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 402414521
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml





